import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { Feed, Sidebar, Widgets } from "src/components/Main";
import tw from "twin.macro";
import fetchTweets from "utils/fetchTweets";
import { Tweet } from "types/typings";
import API_URLS from "src/api_config";

export interface MainPageProps {
  tweets: Tweet[];
}

const Home = ({ tweets }: MainPageProps) => {
  return (
    <StyledWrapper>
      <Head>
        <title>Twitter 2.0 - tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <Sidebar />
        <Feed tweets={tweets} />
        <Widgets />
      </StyledMain>
    </StyledWrapper>
  );
};

export default Home;

const StyledWrapper = styled.section`
  ${tw`max-w-6xl mx-auto max-h-screen`}
`;

const StyledMain = styled.main`
  ${tw`grid grid-cols-9`}
`;

export const getServerSideProps: GetServerSideProps = async () => {
  const tweets = await fetchTweets(API_URLS.tweets);

  return {
    props: {
      tweets,
    },
  };
};
