import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import tw from "twin.macro";

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>세팅</main>
      <footer></footer>
    </section>
  );
};

export default Home;
