import type { NextPage } from "next";
import Head from "next/head";
import { Feed, Sidebar, Widgets } from "src/components/Main";
import styled from "styled-components";
import tw from "twin.macro";

const Home: NextPage = () => {
  return (
    <StyledWrapper>
      <Head>
        <title>Twitter 2.0 - tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <Sidebar />
        <Feed />
        <Widgets />
      </StyledMain>
    </StyledWrapper>
  );
};

export default Home;

const StyledWrapper = styled.section`
  ${tw`max-w-6xl mx-auto max-h-screen`}
`;

const StyledMain = styled.main`
  ${tw`grid grid-cols-9`}
`;
